name: build-on-push

on:
  push:
    branches-ignore:
      - main

jobs:
  build-on-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-jdk
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven

      - name: maven-build-verify
        run: mvn --batch-mode --update-snapshots clean verify
	
      - name: upload-snapshot-to-maven-central
        run: mvn --batch-mode deploy